---
title: "PPDFinal"
author: "Charlie Huemmler"
date: "2022-11-29"
output:
  html_document:
    toc: true
    toc_float: true
    toc_collapsed: true
    code_folding: hide
---

```{r setup}
knitr::opts_chunk$set(
  warning=FALSE,
  message=FALSE,
  results='hide')
```

setup

```{r}
library(tidyverse)
library(sf)
library(lubridate)
library(tigris)
library(RSocrata)
library(purrr)
library(riem)
library(gganimate)
library(ggridges)
library(viridis)
library(scales)


sf::sf_use_s2(FALSE)

options(tigris_class = "sf")
source("https://raw.githubusercontent.com/urbanSpatial/Public-Policy-Analytics-Landing/master/functions.r")

```

Pull in SF data

```{r load meters}
meters <- read.socrata('https://data.sfgov.org/resource/8vzz-qzz9.json') %>% st_as_sf(coords = c('longitude','latitude'),crs = 4326)

```

```{r load trips}
#trips_load <- read.socrata("https://data.sfgov.org/resource/imvp-dq3v.csv?$where=session_start_dt between #'2017-06-01T00:00:00' and '2017-07-01T00:00:00'") 

trips1 <- read.socrata("https://data.sfgov.org/resource/imvp-dq3v.csv?$where=session_start_dt between '2017-06-05T00:00:00' and '2017-06-25T00:00:00'") 


trips <- trips1 %>% mutate(
  start_time = session_start_dt %>% as_datetime(),
  end_time = session_end_dt %>% as_datetime(),
  length_secs = (end_time - start_time),
  rate = gross_paid_amt/as.numeric(length_secs/60),
  hour = start_time %>% hour(),
  dotw = start_time %>% wday(label = T),
  weekend = ifelse(dotw %in% c('Sun','Sat'),1,0)) %>%
  filter(length_secs > 600 & rate < .11)




smalltrips <- trips %>% filter(start_time %>% week == 23) 

```

pull in streets, parks

```{r fig.width=8, fig.height=8}


sfbounds <- c(ymax= 100000, ymin= 63410.51,xmin= 139343.4 , xmax=177200 ) 

water <- area_water('CA', 'San Francisco') %>% st_transform(crs = 7132)  %>% st_crop(y=sfbounds)  %>%
  st_transform(crs = 4326)

streets <- read_sf('streets.geojson') %>% st_transform(crs = 7132)%>% st_crop(y=sfbounds) %>%
  st_transform(crs = 4326)

meters$on_offstreet_type <- meters$on_offstreet_type %>% factor(levels = c("ON", "OFF"))

ggplot()+
  geom_sf(data = water, color = NA, fill = 'lightblue')+
  geom_sf(data = streets%>% filter(classcode ==5))+
  geom_sf(data = streets %>% filter(classcode ==1),size=1.1)+
  geom_sf(data = meters, aes(color = on_offstreet_type), shape = 1, alpha = .5)+
  scale_color_manual(values = c('#7F00FF','#FF7F00'),labels = c("Metered", "Garage"))+
  labs(color = '')+
  theme(legend.position = 'bottom')+
  mapTheme()

ggplot()+
  geom_sf(data = water, color = NA, fill = 'lightblue')+
  geom_sf(data = streets%>% filter(classcode ==5))+
  geom_sf(data = streets %>% filter(classcode ==1),size=1.1)+
  geom_sf(data = meters, color = '#FA7B00', shape = 1)+
  geom_rect(aes(ymax= 37.792,ymin= 37.768,xmin= -122.426 , xmax=-122.386), fill = NA, color = 'red', size =2)+
  labs(color = '')+
  mapTheme()


```


```{r }

#ggplotly(g)
dtbounds <- c(ymax= 37.792,ymin= 37.768,xmin= -122.426 , xmax=-122.386)
dt_meters <- meters %>% st_crop(y=dtbounds) %>% filter(meter_type == 'SS')

ggplot()+
  geom_sf(data = water%>% st_crop(y=dtbounds), color = NA, fill = 'lightblue')+
  geom_sf(data = streets%>% filter(classcode ==5) %>% st_crop(y=dtbounds))+
  geom_sf(data = streets %>% filter(classcode ==1) %>% st_crop(y=dtbounds),size=1.1)+
  geom_sf(data =dt_meters, color = '#FA7B00', shape = 1)+
  mapTheme()


smalltrips_dt <-smalltrips %>% filter(post_id %in% dt_meters$post_id) 

trips_dt <-trips %>% filter(post_id %in% dt_meters$post_id)

trips_dt_avgrate <- trips_dt %>% mutate(
  start_interval15 = floor_date(ymd_hms(session_start_dt), unit = "15 mins")) %>% 
  group_by(start_interval15, street_block) %>%
              summarise(avgrate = mean(rate, na.rm=TRUE))

```








## occupany code
```{r}
# estimate parking occupancy using Sf Park data
# Code by Michael Fichman - mfichman@upenn.edu

# This is a really basic mock-up of how I estimated Pittsburgh parking occupancies to
# the 15 minute interval. I did that project before tidyverse, so it's not code that you
# would find particularly useful.

# There is 100% a better way to do this than to create a bunch of stuff in a mutate
# statement - this is prime for a looped or more algorithmic type of code. It's also very "blunt force"
# in how long it assumes people are parking - there is a lot of rounding.

# This is a panel data setup

# The basic idea is you buy, say, an hour worth of parking, and you "get" 4
# 15 minute "tokens" that can be "dropped" in the occupancy counter of each of the 
# upcoming slots in the panel.

# THis is code just for a few days - but you would want to be doing this for many meters.
# This code assumes you can buy a max of 3 hours of parking (e.g. 12 tokens) - you might need to adjust that.



#dat <- read.socrata("https://data.sfgov.org/resource/imvp-dq3v.json?post_id=591-25480")

# Divide transaction lengths into 15 minute intervals
# THis is done very roughly, you might want to make this more exact
# If a transaction is, say 45 minutes, drop tokens in tokens_00, 01, 02

dat2 <- trips_dt %>%
  mutate(end_interval15 = floor_date(ymd_hms(session_end_dt), unit = "15 mins"),
         start_interval15 = floor_date(ymd_hms(session_start_dt), unit = "15 mins"),
         length = end_interval15 - start_interval15,
         tokens = as.numeric(length )/ 900,
         tokens_00 = ifelse(tokens >= 1, 1, 0),
         tokens_01 = ifelse(tokens >= 2, 1, 0),
         tokens_02 = ifelse(tokens >= 3, 1, 0),
         tokens_03 = ifelse(tokens >= 4, 1, 0),
         tokens_04 = ifelse(tokens >= 5, 1, 0),
         tokens_05 = ifelse(tokens >= 6, 1, 0),
         tokens_06 = ifelse(tokens >= 7, 1, 0),
         tokens_07 = ifelse(tokens >= 8, 1, 0),
         tokens_08 = ifelse(tokens >= 9, 1, 0),
         tokens_09 = ifelse(tokens >= 10, 1, 0),
         tokens_10 = ifelse(tokens >= 11, 1, 0),
         tokens_11 = ifelse(tokens >= 12, 1, 0),
         tokens_12 = ifelse(tokens >= 13, 1, 0),
         tokens_13 = ifelse(tokens >= 14, 1, 0),
         tokens_14 = ifelse(tokens >= 15, 1, 0),
         tokens_15 = ifelse(tokens >= 16, 1, 0),
         tokens_16 = ifelse(tokens >= 17, 1, 0),
         tokens_17 = ifelse(tokens >= 18, 1, 0),
         tokens_18 = ifelse(tokens >= 19, 1, 0),
         tokens_19 = ifelse(tokens >= 20, 1, 0),
         tokens_20 = ifelse(tokens >= 21, 1, 0),
         tokens_21 = ifelse(tokens >= 22, 1, 0),
         tokens_22 = ifelse(tokens >= 23, 1, 0),
         tokens_23 = ifelse(tokens >= 24, 1, 0),
         tokens_24 = ifelse(tokens >= 25, 1, 0))

# Summarize this data by start time and meter

dat3 <- dat2 %>%
  group_by(start_interval15, post_id) %>%
  summarize(tokens_00 = sum(tokens_00),
            tokens_01 = sum(tokens_01),
            tokens_02 = sum(tokens_02),
            tokens_03 = sum(tokens_03),
            tokens_04 = sum(tokens_04),
            tokens_05 = sum(tokens_05),
            tokens_06 = sum(tokens_06),
            tokens_07 = sum(tokens_07),
            tokens_08 = sum(tokens_08),
            tokens_09 = sum(tokens_09),
            tokens_10 = sum(tokens_10),
            tokens_11 = sum(tokens_11),
            tokens_12 = sum(tokens_12),
            tokens_13 = sum(tokens_13),
            tokens_14 = sum(tokens_14),
            tokens_15 = sum(tokens_15),
            tokens_16 = sum(tokens_16),
            tokens_17 = sum(tokens_17),
            tokens_18 = sum(tokens_18),
            tokens_19 = sum(tokens_19),
            tokens_20 = sum(tokens_20),
            tokens_21 = sum(tokens_21),
            tokens_22 = sum(tokens_22),
            tokens_23 = sum(tokens_23),
            tokens_24 = sum(tokens_24))

# Create a panel consisting of all the time/meter observations in the set
# Add a day of the year to each observation, join it to the transaction data
# This might need to be tinkered with to make sure every time period for every meter is included
# There are some weird one-off transactions off hours that might need to be cleaned out

study.panel <- 
  expand.grid(start_interval15=unique(dat3$start_interval15), 
              post_id = unique(dat3$post_id)) %>%
  mutate(doty = yday(start_interval15)) %>%
  left_join(., dat3)

# Estimate occupancy but compiling the current tokens and the previous tokens
# that carry forward - i think (i think) the observations at 15:00 hours are the people who start
# the day parking - not every place has the same metered hours

transaction_panel <- study.panel %>%
  replace(is.na(.), 0) %>%
  arrange(start_interval15) %>%
  group_by(post_id, doty) %>%  
  mutate(lag01 = ifelse(is.na(lag(tokens_01)) == FALSE, lag(tokens_01,1), 0),
         lag02 = ifelse(is.na(lag(tokens_02)) == FALSE, lag(tokens_02,2), 0),
         lag03 = ifelse(is.na(lag(tokens_03)) == FALSE, lag(tokens_03,3), 0),
         lag04 = ifelse(is.na(lag(tokens_04)) == FALSE, lag(tokens_04,4), 0),
         lag05 = ifelse(is.na(lag(tokens_05)) == FALSE, lag(tokens_05,5), 0),
         lag06 = ifelse(is.na(lag(tokens_06)) == FALSE, lag(tokens_06,6), 0),
         lag07 = ifelse(is.na(lag(tokens_07)) == FALSE, lag(tokens_07,7), 0),
         lag08 = ifelse(is.na(lag(tokens_08)) == FALSE, lag(tokens_08,8), 0),
         lag09 = ifelse(is.na(lag(tokens_08)) == FALSE, lag(tokens_09,9), 0),
         lag10 = ifelse(is.na(lag(tokens_10)) == FALSE, lag(tokens_10,10), 0),
         lag11 = ifelse(is.na(lag(tokens_11)) == FALSE, lag(tokens_11,11), 0),
         lag12 = ifelse(is.na(lag(tokens_10)) == FALSE, lag(tokens_12,12), 0),
         lag13 = ifelse(is.na(lag(tokens_10)) == FALSE, lag(tokens_13,13), 0),
         lag14 = ifelse(is.na(lag(tokens_10)) == FALSE, lag(tokens_14,14), 0),
         lag15 = ifelse(is.na(lag(tokens_10)) == FALSE, lag(tokens_15,15), 0),
         lag16 = ifelse(is.na(lag(tokens_10)) == FALSE, lag(tokens_16,16), 0),
         lag17 = ifelse(is.na(lag(tokens_10)) == FALSE, lag(tokens_17,17), 0),
         lag18 = ifelse(is.na(lag(tokens_10)) == FALSE, lag(tokens_18,18), 0),
         lag19 = ifelse(is.na(lag(tokens_10)) == FALSE, lag(tokens_19,19), 0),
         lag20 = ifelse(is.na(lag(tokens_10)) == FALSE, lag(tokens_20,20), 0),
         lag21 = ifelse(is.na(lag(tokens_10)) == FALSE, lag(tokens_21,21), 0),
         lag22 = ifelse(is.na(lag(tokens_10)) == FALSE, lag(tokens_22,22), 0),
         lag23 = ifelse(is.na(lag(tokens_10)) == FALSE, lag(tokens_23,23), 0),
         lag24 = ifelse(is.na(lag(tokens_10)) == FALSE, lag(tokens_24,24), 0)) %>%
  mutate_all(funs(ifelse(is.na(.), 0, .))) %>% 
  mutate(occupancy = tokens_00 + lag01 + lag02 + lag03+ lag04 + lag05 +
           lag06 + lag07 + lag08 + lag09 + lag10 + lag11 + lag12 + lag13+lag14+lag15+lag16+lag17+lag18+lag19+lag20+lag21+lag22+lag23+lag24)

#%>%
 # filter(is.na(occupancy) == FALSE) %>%
  #

# join everything

transaction_panel2 <- transaction_panel %>% mutate(start_interval15 = start_interval15 %>% as_datetime()) %>% select(start_interval15, post_id, occupancy, street_block)

transaction_panel1 <- left_join(transaction_panel2, trips_dt, by = c("start_interval15", "street_block"))

t1 <- transaction_panel %>% filter(post_id == '202-05830')


occ_panel <- transaction_panel1 %>% mutate(
  spot = 1
) %>% group_by(street_block, start_interval15) %>% summarise(
  parked = sum(occupancy),
  total_spots = sum(spot),
  pct_occ = parked/total_spots, 
  avgrate = avgrate
) %>% mutate(start_interval15 = start_interval15 %>% as_datetime(),
             occ_col = ifelse(pct_occ <= 1, pct_occ, 1),
             week = week(start_interval15),
             dotw = wday(start_interval15),
             day = day(start_interval15))
  

meanrate <- mean(occ_panel$avgrate)

occ_panel$avgrate <- ifelse(is.na(occ_panel$avgrate), meanrate, occ_panel$avgrate)

```

```{r over occ analysis}
overoccblock <- occ_panel %>% filter(pct_occ > 1) %>% pull(street_block) %>% unique()

overocctime <- occ_panel %>% filter(pct_occ > 1) %>% pull(start_interval15) %>% unique()

```


```{r}
blocks <- inner_join(dt_meters, smalltrips_dt %>% 
                           select(post_id, street_block) %>% unique())

mpb <- smalltrips_dt %>% 
  group_by(street_block) %>% 
  summarise(meters_per_block = length(unique(post_id)))

block_join <- data.frame(block = NA, geometry = blocks[1,]$geometry) %>% st_sf()

for(block in blocks$street_block %>% unique()){
  block1 <- blocks %>% filter(street_block == block)
  if(nrow(block1) >= 5){
    block2 <- st_union(block1) %>% st_sf()
    block_join <- data.frame(block = block, geometry = block2) %>% add_row(block_join, .)
}
  }


block_join <- block_join %>% slice(2:nrow(block_join))

block_join$id <- seq(1,nrow(block_join))


ggplot(block_join, aes())+
  geom_sf()+
  theme(legend.position = 'none')


```



```{r meter graphing}


t <- occ_panel %>% 
  filter(week == 25) %>%
  group_by(start_interval15) %>% 
  summarize(occ = mean(occ_col),
            block = street_block)  %>% 
  ungroup()

ggplot(t)+ 
  geom_line(aes(start_interval15, occ, color = block, group = block))+
  scale_x_datetime(date_breaks = '1 day', date_labels = '%a')+
  labs(title="Average occupancy of all blocks",
    subtitle="Week 22", 
    x="", y="")+
  theme(legend.position = "none", axis.text.x = element_text(hjust = -1.5))+
  plotTheme()



blocks<-factor(smalltrips_dt$street_block) %>% table() %>% as.data.frame()
meters1<-factor(smalltrips_dt$post_id) %>% table() %>% as.data.frame()




```

```{r}

s1 <- occ_panel %>% group_by(street_block) %>% summarise(occ_avg = mean(occ_col)) %>% arrange(-occ_avg) %>% slice(seq(1,nrow(.),20))

s2 <-occ_panel %>% group_by(street_block) %>% summarise(occ_avg = mean(occ_col)) %>% arrange(-occ_avg) %>% slice(1:20)

g<- occ_panel %>% filter(day == 22 & street_block %in% s2$street_block)

ggplot(g)+
  geom_ridgeline(aes(x = start_interval15, y = reorder(street_block, occ_col), height = occ_col),
                 scale = 1.2)+
  labs(title = ' Occupancy % of 20 Highest Occupancy Blocks', subtitle = 'Thursday June 22, 2017', y = '', x = '' )+
  scale_x_datetime(date_breaks = '3 hours', date_labels = '%H')

h3 <-occ_panel %>% group_by(street_block) %>% summarise(occ_avg = mean(occ_col)) %>% arrange(-occ_avg) %>% left_join(block_join, by = c('street_block' = 'block')) %>% st_sf()

ggplot(h3)+
  geom_sf(aes(color = occ_avg))+
  geom_sf(data = streets%>% filter(classcode ==5) %>% st_crop(y=dtbounds))+
  geom_sf(data = streets %>% filter(classcode ==1) %>% st_crop(y=dtbounds),size=1.1)+
  scale_color_viridis(labels = percent_format(accuracy = 5L))+
  labs(color = "Average \nOccupancy")+
  mapTheme()

```

```{r}

h1 <- occ_panel %>% group_by(street_block) %>% summarise(occ_avg = mean(occ_col)) %>% arrange(-occ_avg) %>% slice(seq(1,nrow(.),100))

h2 <-occ_panel %>% group_by(street_block) %>% summarise(occ_avg = mean(occ_col)) %>% arrange(-occ_avg) %>% slice(1:20)

h<- occ_panel %>% filter(street_block %in% h1$street_block) %>%
  mutate(timeofday = start_interval15 %>% hour() + start_interval15 %>% minute()/60)

ggplot(h)+
  geom_ridgeline(aes(x = timeofday, y = as.factor(-day), height = occ_col))+
  labs(title = 'Occupancy % of 20 Highest Occupancy Blocks', subtitle = 'Thursday \nJune 22, 2017', y = '', x = '' )+
  #scale_x_datetime(date_breaks = '3 hours', date_labels = '%H')+
  facet_wrap(~street_block, scales = 'free')

```

## making da pretty map


#price regeme

```{r}


trips_price <- trips1 %>% mutate(
  start_time = session_start_dt %>% as_datetime(),
  end_time = session_end_dt %>% as_datetime(),
  length_secs = (end_time - start_time),
  rate = gross_paid_amt/as.numeric(length_secs/60/60),
  hour = start_time %>% hour(),
  dotw = start_time %>% wday(label = T),
  weekend = ifelse(dotw %in% c('Sun','Sat'),1,0)) %>%
  filter(length_secs > 600 & rate < 9)


ggplot(trips_price, aes(x = rate))+
  geom_histogram(bins = 50)+
  labs(title = 'Distribution of Hourly Rates',y='',x='')+
  scale_x_continuous(breaks = c(0,2,4,6,8), labels = scales::dollar_format())+ 
  theme(axis.text.y= element_blank())+
  plotTheme()

ggplot(trips_price, aes(y = gross_paid_amt, x = as.numeric(length_secs/60), color = rate))+
  geom_point(alpha = .1)+
  scale_x_continuous(breaks = seq(0,1500,180))+
  scale_y_continuous(labels = scales::dollar_format())+ 
  scale_color_continuous(labels = scales::dollar_format())+
  labs(y = 'Total Paid',x='Total Minutes Purchased', color = 'Hourly \n rate')+
  plotTheme()



ggplot(trips_price)+
  geom_density_ridges2(aes(x = rate, y = hour, group = hour))+
  facet_wrap(~weekend)
```






```{r anim}
anim_panel <- occ_panel %>% filter(start_interval15 %>% day() %in% c(7)) %>% 
  left_join(., block_join, by = c('street_block' = 'block')) %>% na.omit() %>% st_sf() 



mapanim <- ggplot(anim_panel, aes(color = occ_col))+
  geom_sf()+
  scale_color_continuous(labels = scales::percent)+
  mapTheme()+
  labs(title = "Block Occupancy Percent on June 7th",
         subtitle = "15 minute intervals: {current_frame}",
       color = '') +
    transition_manual(start_interval15) +
    mapTheme()
anim_save("map.gif", mapanim, duration = 10)

histanim <- ggplot(anim_panel)+
  geom_histogram(aes(x = occ_col), bins = 10)+
  scale_x_continuous(labels = percent)+
  labs(title = "Distribution of Occupancy % on June 7th",
         subtitle = "15 minute intervals: {current_frame}",x='',y='# of blocks') +
    transition_manual(start_interval15) +
    plotTheme()
anim_save("hist.gif", histanim, duration = 10)


```





## weather
```{r}

#sdf<-riem_stations(network = 'CA_ASOS')
weather.Data <- 
  riem_measures(station = "SFO", date_start = "2017-06-01", date_end = "2017-07-01")

weather.Panel <-  
  weather.Data %>%
  mutate_if(is.character, list(~replace(as.character(.), is.na(.), "0"))) %>% 
  replace(is.na(.), 0) %>%
  mutate(interval15 = ymd_hms(valid) %>% floor_date(unit = "15 mins")) %>%
  mutate(week = week(interval15),
         dotw = wday(interval15, label=TRUE)) %>%
  group_by(interval15) %>%
  summarize(Temperature = max(tmpf),
            Percipitation = sum(p01i),
            Wind_Speed = max(sknt)) %>%
  mutate(Temperature = ifelse(Temperature == 0, 42, Temperature))


```


```{r idne vars add}
park.panel1 <- 
  occ_panel %>% 
  mutate(occ_col = ifelse(pct_occ <= 1, pct_occ, 1)) %>% filter(total_spots > 5) %>% 
  arrange(street_block, start_interval15) %>% 
  group_by(street_block) %>% 
  mutate(lagHour = dplyr::lag(occ_col,1),
         lag2Hours = dplyr::lag(occ_col,2),
         lag3Hours = dplyr::lag(occ_col,3),
         lag12Hours = dplyr::lag(occ_col,12),
         lag1day = dplyr::lag(occ_col,24)) %>% 
  ungroup() %>% 
  left_join(weather.Panel, by = c('start_interval15' = 'interval15')) %>%
  mutate(week = week(start_interval15),
         dotw = wday(start_interval15, label = TRUE),
         hour = hour(start_interval15)) 

```



## training/test split

```{r}
park.train <- filter(park.panel1, week == 24)
park.test <- filter(park.panel1, week == 25)
```



```{r}
model_pred <- function(dat, fit){
  pred <- predict(fit, newdata = dat)}

## start count regressions 

reg4 <- lm(occ_col ~  hour + dotw + Temperature +
             lagHour + lag2Hours + lag3Hours + lag12Hours + lag1day, data=park.train)
reg5 <- lm(occ_col ~  hour + dotw + Temperature + avgrate +
             lagHour + lag2Hours + lag3Hours + lag12Hours + lag1day, data=park.train)


reg4test <- park.test %>%
  mutate(occ.Predict = predict(reg4, park.test),
         occ.Error = occ.Predict - occ_col,
         occ.AbsError = abs(occ.Predict - occ_col),
         occ.APE = (abs(occ.Predict - occ_col)) / occ.Predict,
         reg = 'woPrice') 

reg5test <- park.test %>%
  mutate(occ.Predict = predict(reg5, park.test),
         occ.Error = occ.Predict - occ_col,
         occ.AbsError = abs(occ.Predict - occ_col),
         occ.APE = (abs(occ.Predict - occ_col)) / occ.Predict,
         reg = 'wPrice') 


mean(reg4test$occ.APE, na.rm = T)
mean(reg5test$occ.APE, na.rm = T)

reg4a <- reg4test %>% group_by(start_interval15) %>% summarise(avg_occAPE = mean(occ.APE, na.rm=T),
                                                             occ.Predict1 = mean(occ.Predict, na.rm=T)) %>% mutate(
  avg_occAPE=ifelse(avg_occAPE <0 , NA, avg_occAPE)
)

reg5a <- reg5test %>% group_by(start_interval15) %>% summarise(avg_occAPE = mean(occ.APE, na.rm=T),
                                                             occ.Predict1 = mean(occ.Predict, na.rm=T)) %>% mutate(
  avg_occAPE=ifelse(avg_occAPE <0 , NA, avg_occAPE)
)

ggplot()+
  geom_line(data = ghj, aes(x = start_interval15, y = avg_occAPE))

ggplot(t)+ 
  geom_line(aes(start_interval15, occ))+
  geom_line(data = reg4a, aes(x = start_interval15, y = occ.Predict1), color = 'green')+
  geom_line(data = reg5a, aes(x = start_interval15, y = occ.Predict1), color = 'red')+

  scale_x_datetime(date_breaks = '1 day', date_labels = '%a')+
  labs(title="Predictions on week 25",
    subtitle="Red is hourly rate model, green is without hourly rate, black is observed", 
    x="", y="")+
  theme(legend.position = "none", axis.text.x = element_text(hjust = -1.5))+
  plotTheme()

```

```{r }
week_predictions <- 
  park.Test.weekNest %>% 
  mutate(D_Space_Time_Lags = map(.x = data, fit = reg4, .f = model_pred),
         F_Space_Time_Lags_Temp = map(.x = data, fit = reg5, .f = model_pred))



week_predictions <- week_predictions %>%  
  gather(Regression, Prediction, -data, -week) %>% 
  mutate(Observed = map(data, pull, occ_col),
         Absolute_Error = map2(Observed, Prediction,  ~ abs(.x - .y)),
         MAE = map_dbl(Absolute_Error, mean),
         sd_AE = map_dbl(Absolute_Error, sd)) 


week_predictions %>% 
  dplyr::select(week, Regression, MAE) %>%
  gather(Variable, MAE, -Regression, -week) %>%
  ggplot(aes(week, MAE)) + 
  geom_bar(aes(fill = Regression), position = "dodge", stat="identity") +
 # scale_fill_manual(values = palette5) +
  scale_x_continuous(breaks = c(24,25))+
  labs(title = "Mean Absolute Errors by model specification and training week") +
  plotTheme()

```



